apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-db-config
data:
  WORDPRESS_DB_HOST: wordpress-mysql
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_PASSWORD: your-password
  MYSQL_ROOT_PASSWORD: your-password
  MYSQL_PASSWORD: your-password
  