apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: LoadBalancer # Change to NodePort if LoadBalancer is not supported in your environment
  ports:
    - port: 80 # External port to access WordPress
      targetPort: 80 # Port in the container where WordPress runs
  selector:
    app: wordpress # Match the labels of the WordPress pods
