apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: NodePort
  selector:
    app: wordpress # Match the labels of the WordPress pods
  ports:
    - name: http
      port: 80 # External port to access WordPress
      targetPort: 80 # Port in the container where WordPress runs
      nodePort: 30007