apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: database
        image: mysql:8.0 # Use a supported version of MySQL.
        envFrom:
        - secretRef:
            name: mysql-secret # Reference the secret created earlier.
        ports:
        - containerPort: 3306 # MySQL port.
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql # Mount PV.
      volumes:
      - name: mysql-data 
        persistentVolumeClaim:
          claimName: mysql-pvc # Use PVC.
