apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: production
    app: nginx
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "128Mi"  # Minimum memory guaranteed for the container
          cpu: "250m"      # Minimum CPU guaranteed for the container
        limits:
          memory: "256Mi"  # Maximum memory the container can use
          cpu: "500m"      # Maximum CPU the container can use